### ISSUE TITLE
Extend usage tips

### ISSUE THREAD

**Issue by Panoru84** [cahz/komoot-unlocked-regions#1]
*edit*

works fine in Chrome.

please add the hint to scroll down.
Also developer mode can be closed again after executing the code.

Thanks for this tool 👍

**Comment by cahz** [comment]
Thanks for reporting it. It worked in my setup, but I could verify your problem. I pushed a change, could you please try it out? Scrolling down is no longer required.
(Tested on Chrome 91.0.4472.77)

**Comment by Panoru84** [comment]
yes, now it's on top.  👍
After closing Developer mode it only covers part of the screen.
Not a big thing but just to mention.

**Comment by cahz** [comment]
I have noticed this, but I don't have a quick fix. First after moving or zooming the map the new area gets drawn.
