### ISSUE TITLE
No longer working in Chrome

### ISSUE THREAD

**Issue by LondonRain** [cahz/komoot-unlocked-regions#12]
When I paste the script in Chrome's developer console I now get this error. It used to work up to some months ago:

Uncaught TypeError: Cannot read properties of undefined (reading 'models')
    at <anonymous>:2:42
    
It still works in Firefox.

**Comment by cahz** [comment]
Unfortunately I can't reproduce your issue. Can you please try again to exclude that it was just a one time loading error?

**Comment by LondonRain** [comment]
Can't reproduce either. I'm sorry! :-(
